spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/yanyan
      username: root
      password : root

mybatis:
  type-aliases-package: com.lucas.excel.lucasexcel.model
  mapper-locations: classpath:mapper/*.xml
